// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxbwjqkpflstnjdzavzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4YndqcWtwZmxzdG5qZHphdnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDYxNzUsImV4cCI6MjA2MzA4MjE3NX0.PGoX-diIhQhtd0HB4AuFH1YxkQAi1ArCefz1RIZ5q-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);